### ISSUE TITLE
Running Local in Debugger

### ISSUE THREAD

**Issue by davihar** [seekdavidlee/Eklee-Exams-Api#12]
Hi, what are the steps to successfully run the example in the local debugger.  I think a config file is needed but maybe the scripts create it?  Thanks

**Comment by davihar** [comment]
Also, can you provide an example request.  Thanks

**Comment by seekdavidlee** [comment]
Hi, I have started documentation on the local.settings.json. It is currently in the following branch. Once completed, we should have that in master.

https://github.com/seekdavidlee/Eklee-Exams-Api/blob/local-app-doc/Documentation/LocalDevelopment.md

**Comment by seekdavidlee** [comment]
Documentation is completed.

https://github.com/seekdavidlee/Eklee-Exams-Api/blob/master/Documentation/LocalDevelopment.md

**Comment by davihar** [comment]
Thank you!
